from src.reporting.attribution import (
    AttributionSummary,
    asset_class_attribution,
    attribution_summary,
    contribution_matrix,
    group_attribution,
    normalize_attribution,
    period_attribution,
    sector_attribution,
    strategy_attribution,
    symbol_attribution,
    top_contributors,
)
from src.reporting.dashboard_data import (
    DashboardPayload,
    build_dashboard_data,
    dashboard_time_series,
    dataframe_to_records,
    series_to_points,
    strategy_comparison_dashboard,
)
from src.reporting.exposures import (
    GREEK_COLUMNS,
    ExposureSummary,
    asset_class_exposure,
    exposure_by_group,
    exposure_snapshot,
    greek_exposure,
    normalize_exposures,
    sector_exposure,
    strategy_exposure,
    summarize_exposures,
    top_positions,
)
from src.reporting.export import (
    ExportResult,
    ensure_parent_directory,
    export_dashboard_json,
    export_dashboard_tables,
    export_dataframe_csv,
    export_dataframe_json,
    export_dataframe_parquet,
    export_json,
    export_records_csv,
    export_report_bundle,
    export_table,
    export_text,
    read_csv,
    read_json,
    read_parquet,
)
from src.reporting.performance import (
    PerformanceSummary,
    annualized_return,
    annualized_volatility,
    calculate_returns_from_equity,
    cumulative_returns,
    drawdown_series_from_equity,
    drawdown_series_from_returns,
    equity_curve_from_returns,
    max_drawdown_from_returns,
    performance_table,
    sharpe_ratio,
    sortino_ratio,
    summarize_equity_curve,
    summarize_returns,
    total_return,
    win_rate,
)
from src.reporting.risk_report import (
    ReturnRiskSummary,
    calculate_conditional_value_at_risk,
    calculate_value_at_risk,
    downside_volatility,
    drawdown_report,
    greek_risk_report,
    portfolio_risk_report,
    risk_limit_breaches,
    rolling_volatility,
    summarize_return_risk,
)
from src.reporting.trades import (
    TradeSummary,
    normalize_trades,
    summarize_trades,
    trade_blotter,
    trade_summary_by_strategy,
    trade_summary_by_symbol,
)

__all__ = [
    # performance
    "PerformanceSummary",
    "annualized_return",
    "annualized_volatility",
    "calculate_returns_from_equity",
    "cumulative_returns",
    "drawdown_series_from_equity",
    "drawdown_series_from_returns",
    "equity_curve_from_returns",
    "max_drawdown_from_returns",
    "performance_table",
    "sharpe_ratio",
    "sortino_ratio",
    "summarize_equity_curve",
    "summarize_returns",
    "total_return",
    "win_rate",

    # trades
    "TradeSummary",
    "normalize_trades",
    "summarize_trades",
    "trade_blotter",
    "trade_summary_by_strategy",
    "trade_summary_by_symbol",

    # exposures
    "GREEK_COLUMNS",
    "ExposureSummary",
    "asset_class_exposure",
    "exposure_by_group",
    "exposure_snapshot",
    "greek_exposure",
    "normalize_exposures",
    "sector_exposure",
    "strategy_exposure",
    "summarize_exposures",
    "top_positions",

    # risk report
    "ReturnRiskSummary",
    "calculate_conditional_value_at_risk",
    "calculate_value_at_risk",
    "downside_volatility",
    "drawdown_report",
    "greek_risk_report",
    "portfolio_risk_report",
    "risk_limit_breaches",
    "rolling_volatility",
    "summarize_return_risk",

    # attribution
    "AttributionSummary",
    "asset_class_attribution",
    "attribution_summary",
    "contribution_matrix",
    "group_attribution",
    "normalize_attribution",
    "period_attribution",
    "sector_attribution",
    "strategy_attribution",
    "symbol_attribution",
    "top_contributors",

    # dashboard
    "DashboardPayload",
    "build_dashboard_data",
    "dashboard_time_series",
    "dataframe_to_records",
    "series_to_points",
    "strategy_comparison_dashboard",

    # export
    "ExportResult",
    "ensure_parent_directory",
    "export_dashboard_json",
    "export_dashboard_tables",
    "export_dataframe_csv",
    "export_dataframe_json",
    "export_dataframe_parquet",
    "export_json",
    "export_records_csv",
    "export_report_bundle",
    "export_table",
    "export_text",
    "read_csv",
    "read_json",
    "read_parquet",
]
